%SYSTEMROOT%\SYSTEM32;
%SYSTEMROOT%;
%SYSTEMROOT%\SYSTEM32\WBEM;
%SYSTEMROOT%\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;
C:\PROGRAM FILES (X86)\EGISTEC MYWINLOCKER\X86;
C:\PROGRAM FILES (X86)\EGISTEC MYWINLOCKER\X64;
C:\PROGRAM FILES\COMMON FILES\AUTODESK SHARED\;
C:\MICROSOFT SQL SERVER MIGRATION ASSISTANT 2005 FOR ACCESS\BIN\;
C:\PROGRAM FILES\IBM\GSK8\LIB64;
C:\PROGRAM FILES (X86)\IBM\GSK8\LIB;
C:\XAMPP\PHP;
C:\XAMPP\MYSQL\BIN;
C:\PROGRAM FILES (X86)\CURL\BIN;
C:\PROGRAMDATA\COMPOSERSETUP\BIN;
C:\Program Files (x86)\Heroku\bin;
C:\Program Files (x86)\git\cmd;
C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;
C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;
C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;
C:\Program Files (x86)\Git\cmd;
C:\Program Files (x86)\nodejs\;
D:\Versi ADT\Android\android-sdk\tools;
D:\Versi ADT\Android\android-sdk\platform-tools;
C:\apache-ant\bin;